version: "3.8"
services:
  redis:
    image: "redis:5.0.7-alpine"
    command: redis-server /usr/local/etc/redis/redis.conf
    # command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379-6479:6379"
    volumes:
     - /home/kernux/Documents/thesis/app-redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    mem_limit: 200m
    networks:
      - redis_network

networks:
  redis_network:
    external: true
    name: redis_network
